version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: lab-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=6h"
      - "--web.enable-lifecycle"
    depends_on:
      - node-exporter

  node-exporter:
    image: prom/node-exporter:v1.8.1
    container_name: lab-node-exporter
    ports:
      - "9100:9100"
    command:
      - "--path.rootfs=/host"
    pid: "host"
    restart: unless-stopped
    volumes:
      - /:/host:ro

  grafana:
    image: grafana/grafana:11.2.0
    container_name: lab-grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=lab
      - GF_SECURITY_ADMIN_PASSWORD=lab
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
